# Generated by Django 5.2.4 on 2026-04-15 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='section',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='section',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.academicgroup'),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='academics.academicshift'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'classroom', 'shift')},
        ),
    ]
